FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o wireframez-registry ./cmd/registry

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/wireframez-registry .
EXPOSE 8081
CMD ["./wireframez-registry"]